development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: medimind_production

development:
  adapter: enhanced_postgresql

production:
  adapter: enhanced_postgresql
